### PR TITLE
Fix SVD bug

### LINKED ISSUE #502: SVD bug
I have installed CUDA 10 on my destkop and everything works fine except for SVD. Here is the error, I get

```
 SVD_DeviceTypeKokkos_Compat_KokkosCudaWrapperNode_rank_deficient_UnitTest ...                                                                                                                            
                                                                                                                                                                                                            
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :                                                                                                                                     
                                                                                                                                                                                                            
  Kokkos::Impl::ParallelReduce< Cuda > requested too large team size.                                                                                                                                       
  Traceback functionality not available
```

### PR DESCRIPTION
**Pull request by dalg24**
Closes #502 

The original problem with running SVD on GPUs was too much memory used by a single thread, and thus by a thread team. This commit works around the problem by requiring an extra temporary view to work with. I played around with using `scratch(1)` but was not able to quickly figure it out. I also found some references in other code about using `MemoryPool` and `UniqueToken` together (Mark mentioned Aria). I think this could be a longer term solution, but we have not started working on the performance on this code yet, so I think it's fine for now.

### CODE REVIEW

File: packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp [hunk 1]
```diff
@@ -257,7 +258,8 @@ struct MovingLeastSquaresOperatorImpl
         // available in the comments in SVDFunctor.
         const int team_size = 1;
```
[the remark this answers is not in the document]
Comment (dalg24) [reply packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp]: Want me to use `Kokkos::AUTO` instead?

[the remark this answers is not in the document]
Comment (dalg24) [reply packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp]: I got an error in the MLSOp test with that changes.  Pushed it so you can take a look.

File: packages/Meshfree/src/DTK_DetailsSVDImpl.hpp [hunk 2]
```diff
@@ -210,13 +204,21 @@ struct SVDFunctor
...
-        // worry about sharing.
-        auto offset = 3 * matrix_id * _n * _n;
-        shared_matrix E( _aux.data() + offset, _n, _n );
-        shared_matrix U( _aux.data() + offset + _n * _n, _n, _n );
-        shared_matrix V( _aux.data() + offset + 2 * _n * _n, _n, _n );
+        auto E = Kokkos::subview(
+            _aux, Kokkos::ALL(),
+            Kokkos::make_pair(
+                static_cast<size_t>( 3 * matrix_id * _n ),
+                static_cast<size_t>( 3 * matrix_id * _n + _n ) ) );
```
Comment (dalg24) [inline packages/Meshfree/src/DTK_DetailsSVDImpl.hpp]: Why do you cast to `size_t`?

File: packages/Meshfree/src/DTK_DetailsSVDImpl.hpp [hunk 3]
```diff
@@ -38,15 +38,15 @@ struct SVDFunctor
...
     // This should allow for a certain flexibility later, like using different
     // sized matrices, or using some batching.
-    using matrices_type = Kokkos::View<double *, DeviceType>;
-    using shared_matrix =
-        Kokkos::View<double **, typename ExecutionSpace::scratch_memory_space,
-                     Kokkos::MemoryUnmanaged>;
+    using flat_matrix_type = Kokkos::View<double *, DeviceType>;
+    using aux_matrix_type = Kokkos::View<double **, DeviceType>;
+    using matrix_type =
+        Kokkos::View<double **, Kokkos::LayoutStride, DeviceType>;
```
Comment (dalg24) [inline packages/Meshfree/src/DTK_DetailsSVDImpl.hpp]: I don't get why we would need both `aux_matrix_type` and `matrix_type`.

**Comment by dalg24** [comment]
@aprokop I took the liberty to address my own comments and pushed fixes.  Please have a look and make sure you are ok with the changes.

File: packages/Meshfree/src/DTK_DetailsSVDImpl.hpp [hunk 4]
```diff
@@ -90,7 +89,7 @@ struct SVDFunctor
     }
 
     KOKKOS_INLINE_FUNCTION
-    void trans_nxn( const shared_matrix A, shared_matrix &B ) const
+    void trans_nxn( const matrix_type A, matrix_type &B ) const
```
Comment (dalg24) [inline packages/Meshfree/src/DTK_DetailsSVDImpl.hpp]: Const correctness

**Comment by dalg24** [comment]
@Rombur Would you please review this PR?

File: packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp [hunk 5]
```diff
@@ -253,16 +253,17 @@ struct MovingLeastSquaresOperatorImpl
         auto num_matrices =
             a.extent( 0 ) / ( size_polynomial_basis * size_polynomial_basis );
 
-        // TODO: right now, we hardcode the team size to 1. More information is
-        // available in the comments in SVDFunctor.
-        const int team_size = 1;
+        Kokkos::View<double **, DeviceType> aux( "aux", size_polynomial_basis,
+                                                 3 * num_matrices *
```
Comment (Rombur) [inline packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp]: Where does that 3 come from?

File: packages/Meshfree/src/DTK_DetailsSVDImpl.hpp [hunk 6]
```diff
@@ -83,13 +81,14 @@ struct SVDFunctor
     }
 
     KOKKOS_INLINE_FUNCTION
-    void trans_2x2( const matrix_2x2_type A, matrix_2x2_type &B ) const
+    void trans_2x2( typename matrix_2x2_type::const_type A,
```
Comment (dalg24) [inline packages/Meshfree/src/DTK_DetailsSVDImpl.hpp]: I see another issue with passing `matrix_2x2_type` by value!

File: packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp (hunk 5 above)
Comment (Rombur) [reply packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp]: Reading a commit message it seems it is because we need to store the matrices `E`, `U`, and `V`. Is that right? If so add a comment.

File: packages/Meshfree/src/DTK_DetailsSVDImpl.hpp [hunk 7]
```diff
@@ -38,6 +38,9 @@ struct SVDFunctor
     // We use 1D view of the matrices here to make it as generic as possible.
     // This should allow for a certain flexibility later, like using different
     // sized matrices, or using some batching.
+    // NOTE pass flat::matrix_type and matrix_type by value (or by typename
+    // matrix_type::const_type) butpass matrix_2x2_type by reference (or const
```
Comment (Rombur) [inline packages/Meshfree/src/DTK_DetailsSVDImpl.hpp]: typo `butpass`

File: packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp (hunk 5 above)
Comment (aprokop) [reply packages/Meshfree/src/DTK_DetailsMovingLeastSquaresOperatorImpl.hpp]: That is correct, I added a comment.
